ALTER TABLE trades RENAME COLUMN last_price TO PRICE;

ALTER TABLE trades RENAME COLUMN last_action TO ORDER_TYPE;

ALTER TABLE trades ADD COLUMN ORDER_ID VARCHAR(255);

ALTER TABLE trades ADD COLUMN QUANTITY INT;

ALTER TABLE trades ADD COLUMN SEQUENCE_NUMBER INT;

ALTER TABLE trades ADD COLUMN ORDER_TYPE VARCHAR(255);

